# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.kaitlynkobayashi@gmail.com
author_full_name: Kaitlyn Kobayashi
github_username: kaitlyn-kobayashi
has_additional_authors: false
project_description: bhklab-nnInteractive is a project which tests the nnInteractive
    medical image segmentation model using RECIST and RERECIST input prompts and evaluates
    its performance.
project_name: bhklab-nnInteractive
project_slug: bhklab-nninteractive
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
