[project]
name = "nnInteractive"
version = "1.1.2"
requires-python = ">=3.10, <3.13"
description = "Inference code for nnInteractive"
readme = "readme.md"
license = { file = "LICENSE" }
authors = [
    { name = "Fabian Isensee", email = "f.isensee@dkfz-heidelberg.de"},
    { name = "Helmholtz Imaging Applied Computer Vision Lab" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    'deep learning',
    'image segmentation',
    'semantic segmentation',
    'medical image analysis',
    'medical image segmentation',
    'nnU-Net',
    'nnunet'
]

dependencies = ["monai>=1.5.1,<2",
                "nnunetv2>=2.6",
                "acvl-utils>=0.2.3,<0.3",  # 0.3 may bring breaking changes. Careful!
                "batchgenerators>=0.25.1", 
                "damply>=0.26.0,<0.27"]

[project.urls]
homepage = "https://github.com/MIC-DKFZ/nnInteractive"

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "pre-commit"
]

[build-system]
requires = ["setuptools>=67.8.0"]
build-backend = "setuptools.build_meta"

[tool.codespell]
skip = '.git,*.pdf,*.svg'
#
# ignore-words-list = ''

[tool.setuptools.packages.find]
where = ["."]
include = ["nnInteractive*"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]

[tool.pixi.pypi-dependencies]
torch = { version = ">=2.6,<2.9.0", index = "https://download.pytorch.org/whl/cu126"}
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu126"}
nnInteractive = { path = "./nnInteractive", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.feature.dev.dependencies]
jupyterlab = ">=4.5.6,<5"
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"

[dependency-groups]
dev = ["readii>=1.38.0,<2", "opencv-python>=4.13.0.92,<5"]

[tool.pixi.feature.dev.activation]
# convenient variables which can be used in scripts
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.METADATA = "${PIXI_PROJECT_ROOT}/metadata"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"